# Form implementation generated from reading ui file 'widget_for_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WidgetSetConditions(object):
    def setupUi(self, WidgetSetConditions):
        WidgetSetConditions.setObjectName("WidgetSetConditions")
        WidgetSetConditions.resize(417, 156)
        self.layoutWidget = QtWidgets.QWidget(parent=WidgetSetConditions)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 391, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.text_num_exp = QtWidgets.QLabel(parent=self.layoutWidget)
        self.text_num_exp.setObjectName("text_num_exp")
        self.gridLayout.addWidget(self.text_num_exp, 0, 0, 1, 1)
        self.line_get_num_exp = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.line_get_num_exp.setText("")
        self.line_get_num_exp.setObjectName("line_get_num_exp")
        self.gridLayout.addWidget(self.line_get_num_exp, 0, 1, 1, 1)
        self.text_share_of_greed = QtWidgets.QLabel(parent=self.layoutWidget)
        self.text_share_of_greed.setObjectName("text_share_of_greed")
        self.gridLayout.addWidget(self.text_share_of_greed, 1, 0, 1, 1)
        self.line_get_share_of_greed = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.line_get_share_of_greed.setText("")
        self.line_get_share_of_greed.setObjectName("line_get_share_of_greed")
        self.gridLayout.addWidget(self.line_get_share_of_greed, 1, 1, 1, 1)
        self.text_share_of_thrift = QtWidgets.QLabel(parent=self.layoutWidget)
        self.text_share_of_thrift.setObjectName("text_share_of_thrift")
        self.gridLayout.addWidget(self.text_share_of_thrift, 2, 0, 1, 1)
        self.line_get_share_of_thrift = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.line_get_share_of_thrift.setText("")
        self.line_get_share_of_thrift.setObjectName("line_get_share_of_thrift")
        self.gridLayout.addWidget(self.line_get_share_of_thrift, 2, 1, 1, 1)
        self.button_to_set_condition = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button_to_set_condition.setObjectName("button_to_set_condition")
        self.gridLayout.addWidget(self.button_to_set_condition, 3, 1, 1, 1)

        self.retranslateUi(WidgetSetConditions)
        QtCore.QMetaObject.connectSlotsByName(WidgetSetConditions)

    def retranslateUi(self, WidgetSetConditions):
        _translate = QtCore.QCoreApplication.translate
        WidgetSetConditions.setWindowTitle(_translate("WidgetSetConditions", "Дополнительные параметры"))
        self.text_num_exp.setText(_translate("WidgetSetConditions", "Количество опытов: "))
        self.text_share_of_greed.setText(_translate("WidgetSetConditions", "Доля жадности:       "))
        self.text_share_of_thrift.setText(_translate("WidgetSetConditions", "Доля бережливости:"))
        self.button_to_set_condition.setText(_translate("WidgetSetConditions", "Ввести"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetSetConditions = QtWidgets.QWidget()
    ui = Ui_WidgetSetConditions()
    ui.setupUi(WidgetSetConditions)
    WidgetSetConditions.show()
    sys.exit(app.exec())
